--- #YAML:1.0
name:               POE-Component-Server-BigBrother
version:            0.08
abstract:           POE Component that implements BigBrother daemon functionality
author:
    - Yves Blusseau
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Log::Report:          0.18
    POE:                  0.38
    POE::Component::Pluggable:  0
    POE::Component::Pluggable::Constants:  0
    POE::Component::Server::TCP:  0
    POE::Filter::BigBrother:  0.12
    POE::Filter::Stream:  1.2220
    Test::More:           0.60
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
