# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-BigBrother
version:      0.06
version_from: lib/POE/Component/Server/BigBrother.pm
installdirs:  vendor
requires:
    Carp:                          0
    Log::Report:                   0.18
    POE:                           0.38
    POE::Component::Pluggable:     0
    POE::Component::Pluggable::Constants: 0
    POE::Component::Server::TCP:   0
    POE::Filter::BigBrother:       0.12
    POE::Filter::Stream:           1.2220
    Test::More:                    0.60

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
