--- #YAML:1.0
name:                POE-Component-Server-BigBrother
version:             0.03
abstract:            POE Component that implements BigBrother daemon functionality
license:             perl
author:              
    - Yves Blusseau
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    POE:                           0.38
    POE::Component::Pluggable:     0
    POE::Component::Pluggable::Constants: 0
    POE::Component::Server::TCP:   0
    POE::Filter::BigBrother:       0.12
    Test::More:                    0.60
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
